=== AleBillo/ProgettoOIAML/config/config_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "RPS Configuration Schema",
	"type": "object",
	"properties": {
		"model": {
			"type": "string"
		},
		"preprocessing": {
			"type": "string",
			"default": "greyscale"
		},
		"augmentation": {
			"type": "string",
			"default": "default"
		},
		"optimizer": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"lr": {
					"type": "number",
					"minimum": 0
				},
				"momentum": {
					"type": "number",
					"minimum": 0,
					"default": 0.9
				}
			},
			"required": ["name", "lr"],
			"additionalProperties": false
		},
		"loss": {
			"type": "string"
		},
		"scheduler": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"step_size": {
					"type": "integer",
					"minimum": 1
				},
				"gamma": {
					"type": "number",
					"minimum": 0
				},
				"factor": {
					"type": "number",
					"minimum": 0
				},
				"patience": {
					"type": "integer",
					"minimum": 1
				}
			},
			"required": ["name"],
			"additionalProperties": false
		},
		"training": {
			"type": "object",
			"properties": {
				"batch_size": {
					"type": "integer",
					"minimum": 1
				},
				"num_epochs": {
					"type": "integer",
					"minimum": 1
				},
				"patience": {
					"type": "integer",
					"minimum": 0
				},
				"resume_from_checkpoint": {
					"type": "boolean"
				},
				"checkpoint_path": {
					"type": "string"
				}
			},
			"required": [
				"batch_size",
				"num_epochs",
				"patience",
				"resume_from_checkpoint",
				"checkpoint_path"
			]
		},
		"paths": {
			"type": "object",
			"properties": {
				"train_dir": { "type": "string" },
				"test_dir": { "type": "string" },
				"weight_dir": { "type": "string" }
			},
			"required": ["train_dir", "test_dir", "weight_dir"]
		},
		"logging": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"log_dir": {
					"type": "string"
				}
			},
			"required": ["name", "log_dir"]
		}
	},
	"required": [
		"model",
		"preprocessing",
		"augmentation",
		"optimizer",
		"loss",
		"scheduler",
		"training",
		"paths",
		"logging"
	],
	"additionalProperties": false
}

=== AleBillo/ProgettoOIAML/experiments/ResNet_greyscale_SGD_MSELoss_ReduceLROnPlateau_misto/config.json
{
    "model": "ResNet",
    "preprocessing": "greyscale",
    "augmentation": "default",
    "optimizer": {
        "name": "SGD",
        "lr": 0.01
    },
    "loss": "MSELoss",
    "scheduler": {
        "name": "ReduceLROnPlateau",
        "patience": 3,
        "factor": 0.1
    },
    "training": {
        "batch_size": 32,
        "num_epochs": 30,
        "patience": 5,
        "resume_from_checkpoint": false,
        "checkpoint_path": "export/weights/checkpoint.pth",
        "grad_clip": 2.0
    },
    "paths": {
        "train_dir": "data/misto/train",
        "test_dir": "data/misto/test",
        "weight_dir": "export/weights"
    },
    "logging": {
        "name": "tensorboard",
        "log_dir": "runs/rps_experiment",
        "dashboard_enabled": false
    }
}

=== AleBillo/ProgettoOIAML/config/config.json
{
	"model": "CNN",
	"preprocessing": "greyscale",
	"augmentation": "default",
	"optimizer": {
		"name": "Adam",
		"lr": 0.001
	},
	"loss": "CrossEntropyLoss",
	"scheduler": {
		"name": "StepLR",
		"step_size": 10,
		"gamma": 0.5
	},
	"training": {
		"batch_size": 32,
		"num_epochs": 30,
		"patience": 5,
		"resume_from_checkpoint": false,
		"checkpoint_path": "export/weights/checkpoint.pth"
	},
	"paths": {
		"train_dir": "data/pulito/train",
		"test_dir": "data/pulito/test",
		"weight_dir": "export/weights"
	},
	"logging": {
		"name": "tensorboard",
		"log_dir": "runs/rps_experiment"
	}
}

=== AleBillo/ProgettoOIAML/experiments/VGG_greyscale_Adam_CrossEntropyLoss_ReduceLROnPlateau_pulito/config.json
{
    "model": "VGG",
    "preprocessing": "greyscale",
    "augmentation": "default",
    "optimizer": {
        "name": "Adam",
        "lr": 0.001
    },
    "loss": "CrossEntropyLoss",
    "scheduler": {
        "name": "ReduceLROnPlateau",
        "patience": 3,
        "factor": 0.1
    },
    "training": {
        "batch_size": 32,
        "num_epochs": 30,
        "patience": 5,
        "resume_from_checkpoint": false,
        "checkpoint_path": "export/weights/checkpoint.pth",
        "grad_clip": 2.0
    },
    "paths": {
        "train_dir": "data/pulito/train",
        "test_dir": "data/pulito/test",
        "weight_dir": "export/weights"
    },
    "logging": {
        "name": "tensorboard",
        "log_dir": "runs/rps_experiment",
        "dashboard_enabled": false
    }
}

=== AleBillo/ProgettoOIAML/experiments/ResNet_hsv_Adam_CrossEntropyLoss_StepLR_misto/config.json
{
    "model": "ResNet",
    "preprocessing": "hsv",
    "augmentation": "default",
    "optimizer": {
        "name": "Adam",
        "lr": 0.001
    },
    "loss": "CrossEntropyLoss",
    "scheduler": {
        "name": "StepLR",
        "step_size": 10,
        "gamma": 0.5
    },
    "training": {
        "batch_size": 32,
        "num_epochs": 30,
        "patience": 5,
        "resume_from_checkpoint": false,
        "checkpoint_path": "export/weights/checkpoint.pth",
        "grad_clip": 2.0
    },
    "paths": {
        "train_dir": "data/misto/train",
        "test_dir": "data/misto/test",
        "weight_dir": "export/weights"
    },
    "logging": {
        "name": "tensorboard",
        "log_dir": "runs/rps_experiment",
        "dashboard_enabled": false
    }
}
